common/models/User.php
<?php

namespace common\models;

use common\models\fields\CompletedTaskFields;
use common\models\fields\ReaderUseTimeFields;
use common\models\fields\UserFields;
use common\models\fields\UserGameFields;
use common\models\fields\UserOrgFields;
use DateTime;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\data\ActiveDataProvider;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property string $id
 * @property integer $role
 * @property string $email
 * @property string $name
 * @property string $last_name
 * @property string $auth_key
 * @property string $password_hash
 * @property string $password_reset_token
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $register_code
 * @property string $parent_email
 * @property integer $organization_id
 *
 * @property CompleteTask[] $completeTasks
 * @property Games[] $games
 * @property UserOption[] $userOptions
 * @property UserGames[] $userGames
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    //Roles
    const ROLE_DEFAULT = 0;
    const ROLE_ADMIN = 1;
    const ROLE_SUPER_ADMIN = 2;

    //Rodo independent user age
    const INDEPENDENT_AGE = 16;

    //Default params
    const  DEFAULT_PASSWORD = "Z0s9E8!@#";
    const  DEFAULT_PASSWORD_HASH = '$2y$13$aZ6VEze077Kixka7eIL05ud2r/OG3xVq0nZ.5O981fwsWsLrUqSbe';
    const  DEFAULT_AUTH_KEY = '_xM86bsrTpsKtGvGUpPoBll76FUdeOoB';

    //Account registration status
    const  STATUS_ACTIVE = 1;
    const  STATUS_INACTIVE = 0;

    //Account delay registration days
    const DELETE_TIME = 604800;

    public $inviteStatus;
    public $tag;

    /**
     * Finds user by email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return self::findOne([UserFields::EMAIL => $email]);
    }

    /**
     * Finds admin by email
     *
     * @param string $email
     * @return array|User|null|\yii\db\ActiveRecord[]
     */
    public static function findAdminByEmail($email)
    {
        return self::find()
            ->where([UserFields::EMAIL => $email])
            ->andWhere(['>', UserFields::ROLE, 0])
            ->one();
    }


    /**
     * Return unactivated user array
     * @return array|Task[]|User[]|\yii\db\ActiveRecord[]
     */
    public static function findUnactivated()
    {
        return self::find()->where([UserFields::STATUS => self::STATUS_INACTIVE])->all();
    }

    public static function findIdentity($id)
    {
        return self::findOne([UserFields::ID => $id]);
    }

    /**
     * Authenticates an API user
     *
     * @param string $email email or access token to validate
     * @param string $password password to validate
     * @return User|null authenticated user
     */
//    public static function apiAuth($email, $password)
//    {
//        $user = User::findOne(['email' => $email]);
//
//        // email is mandatory field
//        if (empty($email)) {
//            return null;
//        }
//
//
//        // if password is supplied, authenticate using email and password
//        if (!empty($password)) {
//
//            // if no record matching the requested user
//            if (empty($user)) {
//                return null;
//            }
//
//            // validate password
//            $isPass = $user->validatePassword($password);
//
//            // if password validation fails
//            if (!$isPass) {
//                return null;
//            }
//
//        } else {
//            // if password is empty, authenticate using email value as access token
//            $user = self::findOne([
//                'auth_key' => $email,
//            ]);
//
//            // if no record matching the requested user
//            if (empty($user)) {
//                return null;
//            }
//        }
//
//        // if user validates
//        return $user;
//        return User::findOne(['auth_key' => $auth,]);
//
//    }

    public static function findByPasswordResetToken($token)
    {
        if (!self::isPasswordResetTokenValid($token)) {
            return null;
        }

        return self::findOne([UserFields::PASSWORD_RESET_TOKEN => $token]);
    }

    /**
     * Check is user independent and can create account on it own
     * @param $birthDate
     * @return boolean
     */
    public static function isUserIndependent($birthDate): bool
    {
        $currentDate = new DateTime();
        $userAge = $birthDate->diff($currentDate);
        if($userAge->y >= User::INDEPENDENT_AGE){
            return true;
        }
        return false;
    }

    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int)substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    public static function getLogged(): User
    {
        return self::findOne([UserFields::ID => Yii::$app->user->id]);
    }

    static public function findById($id)
    {
        return self::findOne([UserFields::ID => $id]);
    }

    static public function findByIds($id)
    {
        return self::findAll([UserFields::ID => $id]);
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
    }

    public static function hasTeam($id, $gameId)
    {
        $userGame = UserGame::findByUserIdAndGameId($id, $gameId);

        if ($userGame->team_id === null) {
            return false;
        }
        return true;
    }

    public static function create($email, $name, $lastName,$role = self::ROLE_DEFAULT)
    {
        $user = new User();
        $user->email = $email;
        $user->name = $name;
        $user->last_name = $lastName;
        $user->status = self::STATUS_INACTIVE;
        $user->role = $role;
        $user->register_code = strval(rand(10000000, 99999999));
        $user->password_hash = self::DEFAULT_PASSWORD_HASH;
        $user->auth_key = self::DEFAULT_AUTH_KEY;
        $user->save();
        return $user;
    }

    public function getCreatedDate()
    {
        return $this->created_at;
    }

    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    public function updateFields($params)
    {
        $this->setAttributes($params);
        return $this->save();
    }

    public function setAttributes($values, $safeOnly = true)
    {
        parent::setAttributes($values, $safeOnly);

        if (!empty($values['password'])) {
            $this->setPassword($values['password']);
            $this->generatePasswordResetToken();
        }
    }

    /**
     * Generates new password reset token
     */
    public
    function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name', 'string', 'max' => 45],
            [['name', 'inviteStatus'], 'safe', 'on' => 'search'],

            ['last_name', 'string', 'max' => 45],
            ['last_name', 'safe', 'on' => 'search'],

            [['role'], 'required', 'on' => 'create'],
            [['role'], 'integer', 'on' => 'apiPut'],
            [['role'], 'integer', 'on' => 'create'],

            [['email'], 'required', 'on' => 'create'],
            [['email'], 'string', 'max' => 45],
            [['email'], 'safe', 'on' => 'search'],
            [['email'], 'unique'],

            [['parent_email'], 'string', 'max' => 45],
            [['parent_email'], 'safe', 'on' => 'search'],
            [['parent_email'], 'unique'],

            [['auth_key'], 'required', 'on' => 'create'],
            [['auth_key'], 'string', 'max' => 32],

            [['password_hash'], 'required', 'on' => 'create'],
            [['password_hash'], 'string', 'max' => 255],

            [['status'], 'integer'],
            [['status'], 'safe', 'on' => 'search'],

            [['register_code'], 'integer'],
            [['register_code'], 'safe', 'on' => 'search'],
            [['register_code'], 'unique',],

            [['password_reset_token'], 'string', 'max' => 255],

            [['inviteStatus'], 'integer'],
            [['inviteStatus'], 'safe', 'on' => 'search'],

            [['tag'], 'string'],
            [['tag'], 'safe', 'on' => 'search'],

            [['role', 'email', 'auth_key', 'password_hash', 'name', 'last_name',],
                'filter', 'filter' => '\yii\helpers\HtmlPurifier::process']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'role' => Yii::t('app', 'Rola'),

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\helpers\MailerHelper;
use backend\models\AddOneToGameForm;
use backend\models\CSVImportToGameForm;
use common\models\CompletedTask;
use common\models\fields\GameFields;
use common\models\fields\UserFields;
use common\models\fields\UserGameFields;
use common\models\Game;
use common\models\Task;
use common\models\User;
use common\models\UserGame;
use Yii;
use yii\base\ErrorException;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex($gameId)
    {
        $this->checkAccessByGame($gameId);
        $this->showEndGameFlash($gameId);

        $game = Game::findOne([GameFields::ID => $gameId]);
        $searchModel = new User(['scenario' => 'search']);
        $dataProvider = $searchModel->search($gameId, \Yii::$app->request->get());

        $canMakeTask = Task::findByGameId($gameId) ? true : false;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'game' => $game,
            'canMakeTask' => $canMakeTask,
        ]);
    }

    public function actionImport($gameId)
    {
        $this->checkAccessByGame($gameId);
        $this->checkIfGameEnded($gameId);

        $model = new CSVImportToGameForm();
        $game = Game::findOne([GameFields::ID => $gameId]);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->setUsersArray()) {
                $model->addUsersToGame($gameId);
                Yii::$app->session->setFlash('success', "Dodano użytkowników.");
                return $this->redirect('import');

            } else {
                Yii::$app->session->setFlash('error', "Błąd w strukturze *.csv.");
                return $this->redirect('import');
            }
        }
        return $this->render('import', [
            'model' => $model,
            'game' => $game,
        ]);
    }

    public function actionAdd($gameId)
    {
        $this->checkAccessByGame($gameId);
        $this->checkIfGameEnded($gameId);

        $model = new AddOneToGameForm();
        $game = Game::findOne([GameFields::ID => $gameId]);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->addUserToGame($gameId)) {
                Yii::$app->session->setFlash('success', "Dodano użytkownika.");
                return $this->redirect('add');
            } else {
                Yii::$app->session->setFlash('error', "Uzupełnij dane.");
                return $this->redirect('add');
            }
        }
        return $this->render('add', [
            'model' => $model,
            'game' => $game,
        ]);
    }

    public function actionSelected($gameId)
    {
        $selection = (array)Yii::$app->request->post('selection');

        $type = Yii::$app->request->post('submit');

        if (empty($selection) && $type != 'send-invite-to-all') {
            Yii::$app->session->setFlash('error', "Nikogo nie wybrałeś.");
            return $this->redirect('/game/' . $gameId . '/user');
        }

        switch ($type) {
            case 'send-invited':
                $this->actionSendInvited($selection, $gameId);
                break;
            case 'make-task':
                $this->actionMakeTask($selection, $gameId);
                break;
            case 'send-invite-to-all':
                $this->actionSendInviteToAll($gameId);
                break;
            case 'delete-users':
                $this->actionDeleteFromGame($selection, $gameId);
                break;
        }
    }

    private function actionSendInvited($selectionUserId, $gameId)
    {
        $game = Game::findById($gameId);

        foreach ($selectionUserId as $userId) {
            $user = User::findById($userId);
            if ($user->status == User::STATUS_INACTIVE) {
                MailerHelper::sendActivationInvitation($user, $game);
                UserGame::findByUserIdAndGameId($userId, $gameId)->setToInvited();
            } else {
                if (MailerHelper::sendInviteToGame($user, $game)) {
                    UserGame::findByUserIdAndGameId($userId, $gameId)->setToInvited();
                }
            }

        }

        $this->redirect(['/game/' . $gameId . '/user']);
    }

    private function actionMakeTask($selectionUserId, $gameId)
    {
        $selectedTaskIds = Yii::$app->request->post('task-selecter');

        if (empty($selectedTaskIds)) {
            Yii::$app->session->setFlash('error', "Nie wybrałeś zadania");
            return $this->redirect('/game/' . $gameId . '/user');
        }
        try {
            foreach ($selectionUserId as $userId) {
                foreach ($selectedTaskIds as $taskId) {
                    if (!CompletedTask::findByUserIdAndTaskId($userId, $taskId)) {
                        $task = Task::findById($taskId);
                        CompletedTask::add($userId, $taskId);
                        UserGame::getByUserIdAndGame($userId, $task->game_id)->upScore($task->score);
                        Yii::$app->session->setFlash('success', "Zadania zostało zatwierdzone");
                    }
                }
            }
        } catch (ErrorException $e) {
        }
        $this->redirect(['/game/' . $gameId . '/user/']);
    }

    public function actionSendInviteToAll($gameId)
    {
        $game = Game::findById($gameId);

        $allUnInvitedUserGames = UserGame::find()->where([UserGameFields::GAME_ID => $gameId])->andWhere([UserGameFields::INVITE_STATUS => UserGameFields::INVITE_STATUS_ADD])->all();

        foreach ($allUnInvitedUserGames as $userGame) {

            $user = User::findById($userGame->user_id);

            if ($user->status == User::STATUS_INACTIVE) {
                MailerHelper::sendActivationInvitation($user, $game);
                $userGame->setToInvited();
            } else {
                if (MailerHelper::sendInviteToGame($user, $game)) {
                    $userGame->setToInvited();
                }
            }
        }
        $this->redirect(['/game/' . $gameId . '/user']);
    }

    public function actionDeleteFromGame($selectionsUserId, $gameId)
    {
        foreach ($selectionsUserId as $userId) {
            UserGame::deleteByUserIdAndGameId($userId, $gameId);
        }

        return $this->redirect(['/game/' . $gameId . '/user']);
    }

    protected function findModel($id)
    {
        $model = User::findOne([UserFields::ID => $id]);
        if ($model) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/controllers/UserController.php
<?php

namespace frontend\controllers;


use common\models\User;
use Yii;

/**
 * Site controller
 */
class UserController extends AccessController
{

    public function actionDelete()
    {
        $user = User::getLogged();
        Yii::$app->user->logout(true);
        $user->delete();
        return $this->goHome();
    }


}

backend/views/user/add.php
<?php
use backend\helpers\BreadcrumbHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$breadcrumb = new BreadcrumbHelper();


?>
<!-- BREADCRUMB -->
<section class="content-header">
    <ol class="breadcrumb">
        <?= $breadcrumb->home(); ?>
        <?= $breadcrumb->game($game); ?>
        <?= $breadcrumb->addUserByForm() ?>
    </ol>
</section>
<!-- /BREADCRUMB -->

<section class="content">

    <div class="site-invite">
        <div class="row">
            <div class="col-lg-5">
                <h1> <?= Yii::t('app', 'Dodajesz do gry') ?>
                    <b><?= $game->name ?></b>
                </h1>

                <?php $form = ActiveForm::begin(['id' => 'form-invite']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                <?= $form->field($model, 'name')->textInput(['placeholder' => 'Opcjonalnie','autofocus' => true])?>
                <?= $form->field($model, 'last_name')->textInput(['placeholder' => 'Opcjonalnie','autofocus' => true])?>
                <?= $form->field($model, 'tag')->textInput(['placeholder' => 'Opcjonalnie','autofocus' => true])?>

                <div class="form-group">
                    <?= Html::submitButton(Yii::t('app', 'Dodaj'), ['class' => 'btn btn-primary', 'name' => 'add-by-form']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

backend/views/user/import.php
<?php
use backend\helpers\BreadcrumbHelper;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$breadcrumb = new BreadcrumbHelper();

?>
<!-- BREADCRUMB -->
<section class="content-header">
    <ol class="breadcrumb">
        <?= $breadcrumb->home(); ?>
        <?= $breadcrumb->game($game); ?>
        <?= $breadcrumb->addUserByCSV(); ?>
    </ol>
</section>
<!-- /BREADCRUMB -->

<section class="content">

    <div class="site-invite">
        <div class="row">
            <div class="col-lg-5">
                <h1> <?= Yii::t('app', 'Importujesz graczy do gry') ?>
                    <b><?= $game->name ?></b>
                </h1>

                <?php $form = ActiveForm::begin(['id' => 'form-add-by-csv']); ?>

                <div class="text-info">
                    Dodaj graczy z pliku CSV.  Kolumny w pliku powinny być oddzielone przecinkami i mieć zachowaną następującą kolejność:
                    <span class="text-bold">Mail, Imię, Nazwisko, Etykieta.</span> Przykładowa zawartość pliku:
                    <br><br>
                    <span class="text-red">
                    jan@przyklad.com, Jan, Kowalski, Grupa A
                    tadeusz@przyklad.pl, Tadeusz, Nowak, Grupa B
                    joanna@przyklad.info, Joanna, Iksińska, Grupa B
                    </span>
                    <br><br>
                </div>
                <?= $form->field($model, 'csvFile')->fileInput() ?>
                <div class="form-group">
                    <?= Html::submitButton(Yii::t('app', 'Zaimportuj'), ['class' => 'btn btn-primary', 'name' => 'add-by-csv']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

backend/views/user/index.php
<?php

use backend\converter\TaskConverter;
use backend\helpers\BreadcrumbHelper;
use common\models\Task;
use dosamigos\multiselect\MultiSelect;
use yii\bootstrap\Modal;
use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel common\models */
/* @var $dataProvider yii\data\ActiveDataProvider */

$breadcrumb = new BreadcrumbHelper();
$this->params['gameId'] = $game->id;

?>
<!-- BREADCRUMB -->
<section class="content-header">
    <h1><?= Yii::t('app', 'Gracze w grze ') . $game->name ?></h1>
    <ol class="breadcrumb">
        <?= $breadcrumb->home(); ?>
        <?= $breadcrumb->game($game); ?>
        <?= $breadcrumb->users(); ?>
    </ol>
</section>
<!-- /BREADCRUMB -->

<section class="content">
    <div class="user-index box container box-header with-border">
        <a href="<?= \yii\helpers\Url::to(['game/' . $game->id . '/user/import']) ?>"
           class="btn btn-success" <?php if ($game->isEnd()): echo 'disabled'; endif; ?>">
        <?= Yii::t('app', 'Zaimportuj do gry') ?>
        </a>
        <a href="<?= \yii\helpers\Url::to(['game/' . $game->id . '/user/add']) ?>"
           class="btn btn-success" <?php if ($game->isEnd()): echo 'disabled'; endif; ?>">
        <?= Yii::t('app', 'Dodaj gracza') ?>
        </a>
        <?= Html::beginForm(['user/selected', 'gameId' => $game->id], 'post'); ?>
        <?php if (!$game->isTeamable()): ?>
            <a class="btn btn-primary " data-toggle="modal"
               data-target="#make-task"><?= Yii::t('app', 'Wykonaj zadanie') ?></a>
        <?php endif; ?>
        <a class="btn btn-primary" data-toggle="modal"
           data-target="#send-invited"><?= Yii::t('app', 'Wyślij zaproszenie') ?></a>
        <a class="btn btn-warning" data-toggle="modal"
           data-target="#send-invite-to-all"><?= Yii::t('app', 'Wyślij zaproszenie do wszystkich') ?></a>
        <a class="btn btn-danger " data-toggle="modal"
           data-target="#delete-user"><?= Yii::t('app', 'Usuń z gry') ?></a>
        <div class="box-body">
            <?php
            echo GridView::widget([
                'id' => 'game-grid',
                'emptyText' => Yii::t('app', 'Brak użytkowników'),
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table no-margin small-view sortable table-responsive table table-hover task-table'],
                'columns' => [
                    [
                        'class' => 'yii\grid\CheckboxColumn',
                        'contentOptions' => [
                            'class' => 'checkbox-table',
                        ],
                        'headerOptions' => [
                            'class' => 'checkbox-table',
                        ],
                    ],
                    [
                        'attribute' => 'name',
                        'format' => 'text',
                    ],
                    [
                        'attribute' => 'last_name',
                        'format' => 'text',
                    ],
                    [
                        'attribute' => 'email',
                        'format' => 'email',
                    ],
                    [
                        'attribute' => 'tag',
                        'format' => 'text',
                        'value' => function ($model) {
                            $userGame = \common\models\UserGame::findByUserIdAndGameId($model, $this->params['gameId']);
                            return $userGame->tag;
                        },
                        'filter' => HTML::activeInput("text", $searchModel, "tag", ['class' => 'form-control'])
                    ],
                    [
                        'attribute' => 'inviteStatus',
                        'format' => 'html',
                        'label' => "Status",
                        'value' => function ($model) {
                            $userGame = \common\models\UserGame::findByUserIdAndGameId($model, $this->params['gameId']);
                            return '<span class="invite-status-' . Html::encode($userGame->invite_status) . '">' . $userGame->getInvitedStatusText() . '</span>';
                        },
                        'filter' => Html::activeDropDownList($searchModel, 'inviteStatus', [0 => "Dodany", 1 => "Zaproszony", 2 => "Aktywowany"], ['class' => 'form-control', 'prompt' => 'Pokaż wszystko']),

                    ],
                ],
            ]);
            ?>

            <?php
            Modal::begin([
                'id' => 'make-task',
                'header' => Yii::t('app', 'Wybierz zadanie'),
                'size' => 'modal-xs',
            ]);
            ?>
            <p>
                Wybierz zadanie do wykonania.
            </p>
            <div class="text-center">
                <?= MultiSelect::widget([
                    'name' => "task-selecter",
                    'attribute' => 'selectedValue',
                    'data' => TaskConverter::toArrayIdName(Task::findByGameId($game->id)),
                    'options' =>
                        [
                            'multiple' => 'multiple',
                        ],
                    'clientOptions' =>
                        [
                            'includeSelectAllOption' => true,
                            'numberDisplayed' => 6,
                            'enableCaseInsensitiveFiltering' => true,
                            'nonSelectedText' => Yii::t('app', 'Nic nie wybrano'),
                            'allSelectedText' => Yii::t('app', 'Wybrano wszystkich'),
                            'nSelectedText' => Yii::t('app', 'Wybór dla '),
                            'buttonWidth' => '400px',
                            'maxHeight' => '70px',
                            'inheritClass' => true,
                            'enabledHtml' => true,
                            'selectAllText' => Yii::t('app', 'Zaznacz wszystko'),
                            'filterPlaceholder' => Yii::t('app', 'Szukaj')


                        ],
                ]);
                ?>
            </div>
            <br>
            <button class='btn btn-danger' data-dismiss='modal'><?= Yii::t('app', 'Anuluj') ?> </button>
            <button class='btn pull-right btn-info' type="submit" value="make-task"
                    name="submit"><?= Yii::t('app', 'Wybieram') ?> </button>

            <?php
            Modal::end();
            ?>

            <?php
            Modal::begin([
                'id' => 'send-invited',
                'header' => Yii::t('app', 'Potwierdź wysłanie'),
                'size' => 'modal-xs',
            ]);
            ?>

            <p>
                Po wykonaniu tej akcji użytkownicy, dostaną zaproszenia do gry i będą mogli zobaczyć grę na swojej
                tablicy.
            </p>

            <button class='btn btn-danger' data-dismiss='modal'><?= Yii::t('app', 'Anuluj') ?> </button>
            <button class='btn pull-right btn-info' type="submit" value="send-invited"
                    name="submit"><?= Yii::t('app', 'Potwierdzam') ?> </button>

            <?php
            Modal::end();
            ?>

            <?php
            Modal::begin([
                'id' => 'send-invite-to-all',
                'header' => Yii::t('app', 'Potwierdź wysłanie do wszystkich nie zaproszonych'),
                'size' => 'modal-xs',
            ]);
            ?>

            <p>
                Po wykonaniu tej akcji wszyscy nie zaproszeni użytkownicy, dostaną zaproszenia do gry i będą mogli
                zobaczyć grę na swojej
                tablicy.
            </p>

            <button class='btn btn-danger' data-dismiss='modal'><?= Yii::t('app', 'Anuluj') ?> </button>
            <button class='btn pull-right btn-info' type="submit" value="send-invite-to-all"
                    name="submit"><?= Yii::t('app', 'Potwierdzam') ?> </button>

            <?php
            Modal::end();
            ?>

            <?= Html::endForm(); ?>


            <?php
            Modal::begin([
                'id' => 'delete-user',
                'header' => Yii::t('app', 'Potwierdź usunięcie urzytkownika z gry'),
                'size' => 'modal-xs',
            ]);
            ?>

            <p>
                Czy napewno chcesz usunąć z gry tych graczy ?
            </p>

            <button class='btn btn-danger' data-dismiss='modal'><?= Yii::t('app', 'Anuluj') ?> </button>
            <button class='btn pull-right btn-info' type="submit" value="delete-users"
                    name="submit"><?= Yii::t('app', 'Potwierdzam') ?> </button>

            <?php
            Modal::end();
            ?>

            <?= Html::endForm(); ?>
        </div>
    </div>
</section>