backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\helpers\ArrayHelper;
use backend\models\LoginForm;
use backend\models\SignupForm;
use common\models\fields\GameFields;
use common\models\fields\UserFields;
use common\models\fields\UserOrgFields;
use common\models\Game;
use common\models\User;
use common\models\UserOrg;
use frontend\models\EmailVerificationForm;
use frontend\models\FinishRegistrationForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'registration', 'email-verification', 'finish-registration'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'game', 'invite', 'disabled', 'settings'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionRegistration()
    {
        $this->layout = 'login';
        $model = new SignupForm();

        if ($email = Yii::$app->request->get('email')) {
            $user = User::findByEmail($email);
            $model->id = $user->id;
            $model->email = $user->email;
            $model->name = $user->name;
            $model->lastName = $user->last_name;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $user = $model->signup()) {
            return $this->redirect(['email-verification', 'id' => $user->id]);
        }
        return $this->render('registration', [
            'model' => $model
        ]);
    }

    public function actionEmailVerification($id)
    {
        $this->layout = "login";
        $user = User::findById($id);
        $userBirthDate = Yii::$app->session->get('userBirthDate');

        if ($user == null) {
            throw new BadRequestHttpException(Yii::t('app', 'Błędne ID użytkownika'));
        }

        $model = new EmailVerificationForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->registerByCode($user)) {
            if (User::isUserIndependent($userBirthDate)) {
                return $this->redirect(['site/finish-registration/', 'id' => $user->id]);
            }
            Yii::$app->session->setFlash('error', Yii::t('app', 'Nie możesz założyć konta, nie masz skończone 16 lat'));
            return $this->redirect('registration');
        }
        return $this->render('emailVerification', [
            'model' => $model
        ]);
    }

    public function actionFinishRegistration($id)
    {
        $this->layout = "login";
        $model = new FinishRegistrationForm();
        $user = User::findById($id);

        if($user == null) {
            throw new BadRequestHttpException(Yii::t('app', 'Błędne ID użytkownika'));
        }

        if($user->register_code) {
            throw new BadRequestHttpException(Yii::t('app', 'Konto nie zostało aktywowane'));
        }

        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->setToActive($user))
        {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Założyłeś konto! teraz możesz się zalogować.'));
            return $this->redirect('login');
        }
        return $this->render('finishRegistration', [
            'model' => $model
        ]);
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        } else {

            $this->layout = "login";
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $user = User::findOne([UserFields::ID => Yii::$app->user->identity->getId()]);

        if (!$user->hasOrganization()) {
            return $this->render('noneOrganization');
        }


        $userGames = Game::find()
            ->where(['in', GameFields::OWNER_ORGANIZATION_ID,
                ArrayHelper::map(UserOrg::findAll([UserOrgFields::USER_ID => Yii::$app->user->identity->getId()]), UserOrgFields::ORG_ID)])
            ->all();

        if (!empty($userGames)) {

            $data = [];

            $userOrgsId = ArrayHelper::map(UserOrg::findAll([UserOrgFields::USER_ID => Yii::$app->user->identity->getId()]), UserOrgFields::ORG_ID);

            foreach ($userOrgsId as $userOrgId) {
                $orgStats[0] = $userOrgId;
                $orgStats[1] = Game::find()->where([GameFields::OWNER_ORGANIZATION_ID => $userOrgId])->andWhere([GameFields::STATUS => Game::STATUS_FINISHED])->count();
                $orgStats[2] = Game::find()->where([GameFields::OWNER_ORGANIZATION_ID => $userOrgId])->andWhere([GameFields::STATUS => Game::STATUS_CURRENT])->count();
                $orgStats[3] = Game::find()->where([GameFields::OWNER_ORGANIZATION_ID => $userOrgId])->andWhere([GameFields::STATUS => Game::STATUS_FUTURE])->count();
                array_push($data, $orgStats);
            }
            return $this->render('index', [
                'data' => $data,
            ]);
        }
        return $this->render('emptySite');

    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionDisabled()
    {
        return $this->render('disabledFunctions');
    }

    public function actionSettings()
    {
        return $this->render('settings');
    }
}

frontend/controllers/SiteController.php
<?php

namespace frontend\controllers;


use common\models\User;
use DateTime;
use frontend\assets\IndexAsset;
use frontend\helpers\MailHelper;
use frontend\models\AttributesUpdateForm;
use frontend\models\ContactForm;
use frontend\models\EmailVerificationForm;
use frontend\models\FinishRegistrationForm;
use frontend\models\LoginForm;
use frontend\models\ParentHelpForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SetPasswordInviteForm;
use frontend\models\SignupForm;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public $successUrl = 'Success';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'invite', 'contact', 'about', 'howplay', 'regulations', 'settings', "privacypolicy", 'cookies'],
                'rules' => [
                    [
                        'actions' => ['signup', 'invite', 'regulations', 'privacypolicy','cookies'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'invite', 'contact', 'howplay', 'regulations', 'settings','privacypolicy','cookies'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'error')
            $this->layout = 'unLogged';

        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successLoginByFacebookCallback'],
            ],
        ];
    }

    /*public function successLoginByFacebookCallback($client)
    {
        $attributes = $client->getUserAttributes();

        if (!$attributes['email']) {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Błędny lub brak email\'u'));
            return $this->redirect('/site/login');
        }

        $user = User::findOne(['email' => $attributes['email']]);

        if (!$user) {
            $params = [
                'email' => $attributes['email'],
                'password' => $attributes['id'],
                'login' => "fb" . $attributes['id'],
                'name' => $attributes['first_name'],
                'last_name' => $attributes['last_name']
            ];
            CoreApi::user()->post('', $params);
        }

        $user = User::findOne(['email' => $attributes['email']]);
        Yii::$app->user->login($user, 3600 * 24 * 30);
        return $this->redirect('/');
    }*/

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            IndexAsset::register($this->view);
            $this->layout = 'clear';
            return $this->redirect('/site/login');
        }
        return $this->redirect('/game/index');
    }


    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = 'unLogged';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('index');
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect('/site/login');
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->sendEmail(Yii::$app->params['email'])) {
                Yii::$app->session->setFlash('success', Yii::t('app', 'Dziękujemy za skontaktowanie się z nami.'));
            } else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Coś poszło nie tak, spróbuj ponownie.'));
            }
            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }


    /**
     * Sign user up to app
     *
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        $this->layout = 'unLogged';
        $model = new SignupForm();

        if($email = Yii::$app->request->get('email'))
        {
            $user = User::findByEmail($email);
            $model->id = $user->id;
            $model->email = $user->email;
            $model->name = $user->name;
            $model->lastName = $user->last_name;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $user = $model->signup())
        {
            return $this->redirect(['site/email-verification/', 'id' => $user->id]);
        }
        return $this->render('signup', [
            'model' => $model
        ]);
    }

    /**
     * Verifies new user email
     *
     * @param $id
     * @return string|\yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionEmailVerification($id)
    {
        $this->layout = 'unLogged';
        $user = User::findById($id);
        $userBirthDate = Yii::$app->session->get('userBirthDate');

        if($user == null)
        {
            throw new BadRequestHttpException(Yii::t('app', 'Błędne ID użytkownika'));
        }

        $model = new EmailVerificationForm();
        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->registerByCode($user))
        {
            if(User::isUserIndependent($userBirthDate)){
                return $this->redirect(['site/finish-registration/', 'id' => $user->id]);
            }
            return $this->redirect(['site/parent-help/', 'id' => $user->id]);
        }
        return $this->render('emailVerification', [
            'model' => $model
        ]);
    }

    /**
     * Parent - user email request to finish registration
     *
     * @param $id
     * @return string
     * @throws BadRequestHttpException
     */
    public function actionParentHelp($id)
    {
        $this->layout = 'unLogged';
        $user = User::findById($id);

        if($user == null) {
            throw new BadRequestHttpException(Yii::t('app', 'Błędne ID użytkownika'));
        }

        if($user->register_code) {
            throw new BadRequestHttpException(Yii::t('app', 'Konto nie zostało aktywowane'));
        }

        $model = new ParentHelpForm();
        if($model->load(Yii::$app->request->post()) && $model->validate() && $model->send($user))
        {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Prośba została wyłana, poproś opiekuna o pomoc'));
            return $this->redirect(['/site/login/']);
        }
        return $this->render('parentHelp', [
            'model' => $model
        ]);
    }

    /**
     * Finish registration process
     *
     * @param $id
     * @return string|\yii\web\Response
     * @throws BadRequestHttpException
     */
    public function actionFinishRegistration($id)
    {
        $this->layout = 'unLogged';
        $model = new FinishRegistrationForm();
        $user = User::findById($id);

        if ($user == null) {
            throw new BadRequestHttpException(Yii::t('app', 'Błędne ID użytkownika'));
        }

        if ($user->register_code) {
            throw new BadRequestHttpException(Yii::t('app', 'Konto nie zostało aktywowane'));
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->setToActive($user)) {
            Yii::$app->session->setFlash('success', Yii::t('app', 'Założyłeś konto! teraz możesz się zalogować.'));
            return $this->redirect('login');
        }

        return $this->render('finishRegistration', [
            'model' => $model
        ]);
    }

    public function actionSignupWithParent()
    {
        $this->layout = 'unLogged';
        $model = new SignupForm();

        if($email = Yii::$app->request->get('email'))
        {
            $user = User::findByEmail($email);
            $model->id = $user->id;
            $model->email = $user->email;
            $model->name = $user->name;
            $model->lastName = $user->last_name;
            $model->parentHelp = true;
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $this->redirect(['site/finish-registration-with-parent', 'id' => $model->id]);
        }

        return $this->render('signupWithParent', [
            'model' => $model,
            'childEmail' => $model->email
        ]);
    }

    public function actionFinishRegistrationWithParent($id)
    {
        $this->layout = 'unLogged';
        $model = new FinishRegistrationForm();
        $user = User::findById($id);

backend/views/site/disabledFunctions.php
<?php

?>

<section class="content-header">
    <h1><?= Yii::t('app', 'Wyłączone funkcje dla zakończonej gry') ?></h1>
</section>
<section class="content">
    <div class="box container box-header with-border">
        <ul>
            <li><?=Yii::t('app','Gra')?></li>
            <ul>
                <li><?=Yii::t('app','Edycja obecnej gry')?></li>
            </ul>
            <li><?=Yii::t('app','Gracze')?></li>
            <ul>
                <li><?=Yii::t('app','Zapraszanie nowych graczy do gry')?></li>
            </ul>
            <li><?=Yii::t('app','Zadania')?></li>
            <ul>
                <li><?=Yii::t('app','Dodawanie nowych zadań do gry')?></li>
                <li><?=Yii::t('app','Edycja obecnych zadań w grze')?></li>
            </ul>
            <li><?=Yii::t('app','Drużyny')?></li>
            <ul>
                <li><?=Yii::t('app','Dodawanie nowych drużyn do gry')?></li>
                <li><?=Yii::t('app','Edycja nowych drużyn w grze')?></li>
                <li><?=Yii::t('app','Dodawanie graczy do drużyny')?></li>
                <li><?=Yii::t('app','Usuwanie graczy z drużyny')?></li>
            </ul>
        </ul>
    </div>
</section>

backend/views/site/emailVerification.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\EmailVerificationForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>

<div class="container">
    <br>
    <br>
    <br>
    <div class="login-logo">
        <img src="/images/logo_kompas.png">
    </div>
    <br>

    <div class="login-box-body col-xs-12">
        <div class="col-xs-12 text-center">
            <h1><?= \Yii::t('app', 'Zweryfikuj email') ?></h1>
        </div>
        <div class="col-xs-12 text-justify">
            <h4><?= \Yii::t('app', 'Na podany przez Ciebie adres email został wysłany kod werfikacyjny. Wpisz go w polu poniżej aby potwierdzić poprawność adresu email.') ?>  </h4>
            <br>
            <h4><?= \Yii::t('app', 'Jeśli nie podasz kodu do dnia ') . "<b>" . date('Y-m-d', strtotime("+10 day")) . "</b>" . \Yii::t('app', ' twoje dane podane w poprzednim kroku zostaną usunięte.') ?> </h4>
            <br>
            <h3><?= \Yii::t('app', 'Podaj kod werifikacyjny') ?></h3>
            <?php $form = ActiveForm::begin(['id' => 'email-verification-form']); ?>
            <div class="no-padding col-xs-12">
                <?= $form->field($model, 'registerCode')->textInput(['autofocus' => true, 'placeholder' => \Yii::t('app', 'Kod weryfikacyjny'), 'class' => 'signup-input form-control'])->label(false) ?>
            </div>
            <?= Html::submitButton(Yii::t('app', 'Dalej'), ['class' => 'btn btn-primary signup-button', 'name' => 'signup-button']) ?>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/emptySite.php
<?php

?>

<div class="container text-center">

    <b><h2>Nie masz utworzonych gier.</h2>
            <h1>Utwórz nową grę, zadania i zaproś graczy do zabawy.</h1></b>

</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        <?= Yii::t('app', '') ?>
    </p>
    <p>
        <?= Yii::t('app', '') ?>
    </p>

</div>

backend/views/site/finishRegistration.php
9o<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\FinishRegistrationForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>


<div class="container">

    <br>
    <br>
    <div class="login-logo">
        <img src="/images/logo_kompas.png">
    </div>
    <br>

    <div class="login-box-body">
    <?php $form = ActiveForm::begin(['id' => 'finish-registration-form']); ?>

    <h3><?= Yii::t('app', 'Podaj hasło') ?></h3>
    <div class="no-padding col-xs-12">
        <?= $form->field($model, 'password')->passwordInput(['autofocus' => true, 'placeholder' => \Yii::t('app', 'Hasło'), 'class' => 'signup-input form-control'])->label(false) ?>
    </div>
    <h3><?= Yii::t('app', 'Powtórz hasło') ?></h3>
    <div class="no-padding col-xs-12">
        <?= $form->field($model, 'passwordRepeat')->passwordInput(['autofocus' => true, 'placeholder' => \Yii::t('app', 'Hasło'), 'class' => 'signup-input form-control'])->label(false) ?>
    </div>
    <div class="col-xs-12 signup-checkbox text-center">
        <?= $form->field($model, 'regulations')
            ->checkbox(['template' =>
                "<div class='col-xs-12 col-xs-12 signup-checkbox'>{input}" .
                Yii::t('app', ' Oświadczam, iż zapoznałem się oraz akceptuje postanowienia ') .
                "<a href='" . \yii\helpers\Url::to(['/site/regulations']) . "'><b>Regulaminu Serwisu Kompas</b></a>" .
                Yii::t('app', ' oraz ') .
                "<a href='" . \yii\helpers\Url::to(['/site/privacypolicy']) . "'><b>Polityki Prywatności Serwisu Kompas</b></a>" .
                "</div>\n<div class='col-xs-12'>{error}</div>",])
        ?>
    </div>

    <?= Html::submitButton('Utwórz konto', ['class' => 'btn btn-primary signup-button', 'name' => 'signup-button']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/site/index.php
<?php

use common\models\Organization;

?>


<section class="content-header">
    <div class="row row-clear">
        <?php
        foreach ($data as $dat) {
            ?>
            <div class="col-xs-12">
            <h3><?= Yii::t('app', 'Statystyki dla organizacji ') ?>  <?= Organization::findOne([\common\models\fields\OrganizationFields::ID => $dat[0]])->name ?></h3>

            <!-- End Game counter-->
            <div class="col-xs-4">
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3><?= $dat[1] ?></h3>
                        <p><?= Yii::t('app', 'Ilość twoich gier zakończonych') ?></p>
                    </div>
                    <div class="icon">
                        <i class="fa  fa-stop"></i>
                    </div>
                </div>
            </div>
            <!-- /End game counter-->

            <!-- Now game counter-->
            <div class="col-xs-4">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3><?= $dat[2] ?></h3>
                        <p><?= Yii::t('app', 'Ilość twoich gier trwających') ?></p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-play"></i>
                    </div>
                </div>
            </div>
            <!-- /Now game counter-->

            <!-- Be game counter-->
            <div class="col-xs-4">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3><?= $dat[3] ?></h3>
                        <p><?= Yii::t('app', 'Ilość twoich gier przyszłych') ?></p>
                    </div>
                    <div class="icon">
                        <i class="fa  fa-step-forward"></i>
                    </div>
                </div>
            </div>
            <!-- /be game counter-->
            </div>
            <?php
        }
        ?>
    </div>
</section>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \common\models\LoginForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = Yii::t('app', 'Login');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="login-box">
    <div class="login-box">
        <div class="login-logo">
            <img src="/images/logo_kompas.png">
        </div>
        <div class="login-box-body">
            <p class="login-box-msg"><?= Yii::t('app', 'Zaloguj się do panelu administratora') ?></p>
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

            <div class="form-group has-feedback">
                <?= $form->field($model, 'email')
                    ->textInput(['autofocus' => true, 'class' => "form-control", "placeholder" => Yii::t('app', 'Email')])
                    ->label(false) ?>
                <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            </div>

            <div class="form-group has-feedback">
                <?= $form->field($model, 'password')
                    ->textInput(['autofocus' => true, 'class' => "form-control", 'type' => 'password', "placeholder" => Yii::t('app', 'Hasło')])
                    ->label(false) ?>
                <span class="glyphicon glyphicon-lock form-control-feedback"></span>
            </div>
            <div class="row">

                <div class="col-xs-8">
                    <?= $form->field($model, 'rememberMe')
                        ->checkbox(['template' => '<div style="padding-top: 7px;padding-left: 4px;">{input}' . Yii::t('app', ' Zapamiętaj mnie') . '</div>'])
                    ?>
                </div>
                <div class="col-xs-4">
                    <?= Html::submitButton(Yii::t('app', 'Zaloguj'), ['class' => 'btn btn-success btn-block btn-flat', 'name' => 'login-button']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>

        <div class="login-box">
            <div class="login-box-body">
                <div class="row">
                    <div class="col-xs-1"></div>
                    <div class="col-xs-11">
                        <p>
                            <?= Yii::t('app', 'Nie jesteś jeszcze administratorem ?') ?>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-3"></div>
                    <div class="col-xs-9">
                        <a href="<?= \yii\helpers\Url::to(['/site/registration']) ?>"
                           class="btn btn-warning btn-block btn-flat">
                            <?= Yii::t('app', 'Dołącz do grona administratorów') ?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/site/noneOrganization.php
<?php

?>

<div class="container text-center">
    <center>
        <b><h2>Nie podlegasz jeszcze żadnej organizacji.</h2>
            <h1>Utwórz nową aby dołaczyć do zabawy.</h1></b>
            <br/>
            <br/>
            <br/>
            <a href="<?= \yii\helpers\Url::to(['/organization/create']) ?>"
               class="btn btn-block btn-primary">
                <?= Yii::t('app', 'Stwórz nową organizację') ?>
            </a>
        </div>
    </center>
</div>

backend/views/site/registration.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model \frontend\models\SignupForm */

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

?>
<div class="container">
    <br>
    <br>
    <br>
    <div class="login-logo">
        <img src="/images/logo_kompas.png">
    </div>
    <br>
    <div class="login-box-body">

        <h2><?= Yii::t('app', 'Zarejestruj się jako administrator') ?></h2>
        <?php $form = ActiveForm::begin(['id' => 'signup-form']); ?>

        <h3><?= Yii::t('app', 'Podaj email') ?></h3>
        <div class="">
            <?= $form->field($model, 'email')->textInput(['autofocus' => true, 'type' => 'email', 'disabled' => $model->id, 'placeholder' => \Yii::t('app', 'Email'), 'class' => 'signup-input form-control'])->label(false) ?>
        </div>
        <h3><?= Yii::t('app', 'Podaj imię') ?></h3>
        <div class=" ">
            <?= $form->field($model, 'name')->textInput(['autofocus' => true, 'placeholder' => \Yii::t('app', 'Imie'), 'class' => 'signup-input form-control'])->label(false) ?>
        </div>
        <h3><?= Yii::t('app', 'Podaj nazwisko') ?></h3>
        <div class=" ">
            <?= $form->field($model, 'lastName')->textInput(['autofocus' => true, 'placeholder' => \Yii::t('app', 'Nazwisko'), 'class' => 'signup-input form-control'])->label(false) ?>
        </div>
        <h3><?= Yii::t('app', 'Data urodzenia') ?></h3>

        <div class="row">
            <div class=" col-xs-4">
                <?= $form->field($model, 'birthDay')->textInput(['type' => 'number', 'autofocus' => true, 'placeholder' => \Yii::t('app', 'DD'), 'class' => 'signup-input form-control'])->label(false) ?>
            </div>
            <div class=" col-xs-4 small-padding">
                <?= $form->field($model, 'birthMonth')->textInput(['type' => 'number', 'autofocus' => true, 'placeholder' => \Yii::t('app', 'MM'), 'class' => 'signup-input form-control'])->label(false) ?>
            </div>
            <div class=" col-xs-4">
                <?= $form->field($model, 'birthYear')->textInput(['type' => 'number', 'autofocus' => true, 'placeholder' => \Yii::t('app', 'RRRR'), 'class' => 'signup-input form-control'])->label(false) ?>
            </div>
        </div>
        <div class=" ">
            <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className()) ?>
        </div>

        <div class=" row ">
            <div class="col-xs-4">
                <a class="btn btn-primary btn-block btn-flat"
                   href="<?php echo yii\helpers\Url::to(['/site/login']); ?>">
                    <?= Yii::t('app', 'Powrót') ?>
                </a>
            </div>
            <div class="col-xs-4"></div>
            <div class="col-xs-4">
                <?= Html::submitButton('Dalej', ['class' => 'btn btn-success btn-block btn-flat', 'name' => 'signup-button']) ?>
            </div>
        </div>
        <p style="color:#ffffff">chuj</p>

    </div>

    <?php ActiveForm::end(); ?>
</div>

<br>
<br>
<br>
<br>
<br>

backend/views/site/settings.php
<?php

?>

<div class="container text-center">

    <h2> TO DO </h2>
    <?php //todo ?>
</div>